name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image (PR only)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: cloudiepad/sentry-terraform-toolkit:pr-${{ github.event.pull_request.number || github.run_number }}

  push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cloudiepad
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python3 setup.py --version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build and push Docker image (latest and version tags)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            cloudiepad/sentry-terraform-toolkit:latest
            cloudiepad/sentry-terraform-toolkit:${{ steps.get_version.outputs.version }}